/** 独立中文离线报告：内嵌数据与图表代码，无远程脚本、字体或请求。 */
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const num = (n, digits = 1) => Number.isFinite(n) ? n.toFixed(digits) : '—';
const titles = {
  breathSupport:'可能需要改善气息支持', pressedPhonation:'可能存在偏紧的发声', breathyClosure:'可能存在漏气的发声',
  drift:'持续音音高漂移', instability:'持续音音高波动', tailFade:'持续音尾部响度衰减', pitchFlat:'相对参考偏低', pitchSharp:'相对参考偏高', pitchError:'相对参考音高偏差', onsetEarly:'相对参考起音偏早', onsetLate:'相对参考起音偏晚',
  tooShort:'录音过短', noVoice:'没有可靠有声片段', lowVoicedCoverage:'有声覆盖不足', lowPitchClarity:'音高周期性较低', mixedSource:'伴奏可能干扰', unknownSource:'声源类型未知', separationArtifacts:'分离人声可能含残留', clipping:'采样峰接近满幅', lowRecordingLevel:'录音电平偏低',
  needDryRecording:'需要补录无伴奏干声', noStableRegions:'没有可靠持续音区间', insufficientRepeatedEvidence:'缺少重复证据', breathSupportInsufficientEvidence:'气息支持假设证据不足', pressedPhonationInsufficientEvidence:'偏紧发声假设证据不足', breathyClosureInsufficientEvidence:'漏气发声假设证据不足',
  alignmentUntrusted:'对齐尚未验证', selfComparison:'演唱与参考相同', performanceInsufficient:'演唱证据不足', referenceInsufficient:'参考证据不足', sourceUnverified:'声源尚未核实', referenceInconsistent:'参考音高证据不稳定', insufficientOverlap:'有效重叠时间不足', insufficientCoverage:'有效匹配不足',
  alignmentContentMismatch:'至少一个窗口的独立内容匹配未达到门限', alignmentContentNonFixedOffset:'独立内容窗口不支持同一固定偏移', alignmentWeakCorrelation:'伴奏包络相关性不足',alignmentWeakLocalMatch:'局部包络匹配不足',alignmentNonFixedOffset:'局部偏移不一致',alignmentAmbiguous:'存在强度接近的其它对齐候选',alignmentTooShort:'音频不足以提供有跨度的对齐证据',alignmentNoEnvelopeVariation:'伴奏变化不足以估计偏移',alignmentAnchorsTooClose:'对齐锚点跨度不足',
  intentionalExpression:'主动的音乐表达', volumeChange:'音量变化', reverb:'混响', separationResidual:'音源分离残留', vowelChange:'元音变化', pitchTrackingError:'音高跟踪误差',
};
const metricNames = {
  driftCents:'首尾音高差（音分）', slopeCentsPerSec:'音高变化（音分/秒）', durationSec:'时长（秒）', residualSpreadCents:'去趋势音高波动（音分）', levelDropDb:'首尾响度差（dB）', pitchDriftCents:'音高漂移（音分）',
  repetitions:'重复区间数', meanTailDropDb:'平均尾部响度差（dB）', meanPitchDriftCents:'平均音高漂移（音分）', regionIds:'相关持续音区间', baselineH1H2Db:'本次录音 H1-H2 基线（dB）', observedH1H2Db:'候选区间 H1-H2（dB）', baselineHarmonicRatio:'谐波占比基线', observedHarmonicRatio:'候选区间谐波占比', highRegionCount:'较高音区间数', highH1H2Db:'较高音区 H1-H2（dB）', baselineRmsDb:'响度基线（dB）', highRmsDb:'较高音区响度（dB）',
  medianCents:'有符号音高偏差中位数（音分）', absMedianCents:'绝对音高偏差中位数（音分）', inTuneRatio:'配对音高命中比例', comparedSec:'配对秒数', octaveDifferenceRatio:'近八度差比例', octaveShiftSemitones:'整句近八度差（半音）', offsetMs:'起音相对参考偏移（毫秒）', referenceTime:'参考起音（秒）', performanceTime:'演唱起音（秒）',
};
const parameterNames = { frameSize:'分析窗采样数',hopSec:'窗移（秒）',gateRms:'响度门限',minClarity:'周期性门限',minFreq:'最低检测频率（Hz）',maxFreq:'最高检测频率（Hz）',minEffectiveVoicedSec:'最低有效有声秒数',spectralFeatures:'频谱特征',hitCents:'命中阈值（音分）',yinThreshold:'YIN 门限',silenceGapSec:'乐句静音间隔（秒）',sustainedMinSec:'最短持续音（秒）',sustainedSpanCents:'持续音区间音高跨度（音分）',hopSamples:'窗移采样数',timestamp:'时间戳位置',h1h2Correction:'H1-H2 校正' };
const label = code => titles[code] || code;
const valueText = (key,value) => value == null ? '—' : typeof value === 'number' ? num(value,3) : typeof value === 'boolean' ? (value?'启用':'关闭') : key==='timestamp' && value==='windowCentre' ? '分析窗中心' : key==='h1h2Correction' && value==='none' ? '未校正' : Array.isArray(value) ? value.join('、') : typeof value==='string' ? value : JSON.stringify(value);
const metrics = values => `<dl>${Object.entries(values).map(([k,v]) => `<dt>${escape(metricNames[k] || parameterNames[k] || k)}</dt><dd>${escape(valueText(k,v))}</dd>`).join('')}</dl>`;
const severity = value => ({notice:'观察提示',warning:'建议关注',low:'低',moderate:'中等',high:'高'}[value] || value);

function practice(item) {
  if (Number.isFinite(item.metrics?.octaveShiftSemitones) && Math.abs(item.metrics.octaveShiftSemitones) >= 11 && item.metrics?.octaveDifferenceRatio >= 0.7) return '先回听这一整句，核对是否主动换八度、移调或出现追踪误差。以舒适音区哼唱参考短句，确认旋律相同后再比较；不要为了匹配参考强行升高或压低声音。';
  if (['pitchFlat','pitchSharp','pitchError'].includes(item.code)) return '截取 3–5 个音，先听参考，再以舒适音量哼唱同一旋律。确认移调与八度后逐音比较，连续稳定 3 次再接回整句。';
  if (['onsetEarly','onsetLate'].includes(item.code)) return '回听该乐句伴奏，轻拍节奏并标出起音拍点；先说歌词节奏，再唱短句。保持同一固定对齐，不用整曲拉伸消除抢拍或拖拍。';
  if (item.code === 'tailFade') return '以自然音量唱一段舒适音高的 3 秒「呜」，在不憋气、不加力的前提下保持尾部音量。再唱同样长度的短句，比较是否仍衰减；主动弱收属于表达，不必纠正。';
  if (item.code === 'drift') return '先听一个舒适的目标音，再轻哼 3 秒并观察曲线；保持自然音量和元音，休息后重录 3 次。先验证能否稳定，不延长到缺气或用力。';
  if (item.code === 'instability') return '用轻哼或唇颤音唱 3 秒舒适音高，再换成自然音量的「呜」。比较非周期波动是否减少；主动颤音或滑音应结合回听，不当作错误。';
  if (item.code === 'breathSupport') return '以舒适音高和自然音量唱 3–5 秒「呜」，保持音量与音高平稳；再唱同样长度的短句，比较尾部变化。不要延长到缺气或用力。';
  if (item.code === 'pressedPhonation') return '先做轻柔的唇颤音或哼鸣，再以自然说话音量唱同一元音；比较声音和紧张感，避免追求音量。';
  if (item.code === 'breathyClosure') return '在无伴奏近距离录音中，先轻哼，再轻声转为「呜」或「依」并保持 3 秒；比较气声、音量和稳定性，不刻意夹紧喉部。';
  return '无伴奏补录 3–5 秒舒适音高持续元音和一句短乐句，结合回听验证。';
}

export function renderReport(report, { audioUrl, referenceUrl = null, alignmentEvidence = null } = {}) {
  const data = JSON.stringify(report).replace(/</g, '\\u003c');
  const issues = report.issues ?? [], hypotheses = report.hypotheses ?? [];
  const duration = item => item.metrics?.comparedSec ?? item.metrics?.durationSec ?? item.end-item.start;
  const priority = issues.filter(item => !['pitchFlat','pitchSharp','pitchError','onsetEarly','onsetLate'].includes(item.code) || duration(item)>=1).sort((a,b) => ((b.severity==='warning')-(a.severity==='warning')) || (duration(b)-duration(a))).slice(0,3);
  const range = report.summary?.robustRange, comparison = report.comparison;
  const title = report.metadata?.label ?? '本地录音报告';
  const ce=alignmentEvidence?.contentEvidence;
  const alignmentNote = alignmentEvidence ? `<p class="muted">固定偏移候选：${num(alignmentEvidence.offsetSec,3)} 秒。${escape((alignmentEvidence.reasons??[]).map(label).join('；'))}${ce?`；各窗口内容相关性 ${escape((alignmentEvidence.anchors??[]).map(a=>num(a.contentCorrelation,3)).join(' / '))}；每处至少 ${num(ce.minSupportingCorrelation??ce.minCorrelation,2)}，至少 ${ce.requiredStrongAnchors??alignmentEvidence.anchors.length} 处达到 ${num(ce.strongCorrelation??ce.minCorrelation,2)}。`:''}${alignmentEvidence.alignmentTrusted?'内容证据支持固定对齐，仍建议回听核对版本。':'当前不评分，需要回听公共乐句后提供独立锚点验证。'}</p>` : '';
  const row = item => `<article><div class="row"><strong>${escape(label(item.code))}</strong><button data-start="${Number(item.start)||0}" data-end="${Number(item.end)||0}">回听 ${num(item.start)}–${num(item.end)} 秒</button></div><p class="muted">${escape(item.severity ? severity(item.severity) : '可信度：' + severity(item.confidence))}</p>${item.metrics ? metrics(item.metrics) : ''}${item.evidence ? `<p><b>证据：</b></p>${typeof item.evidence==='object' ? metrics(item.evidence) : `<p>${escape(item.evidence)}</p>`}` : ''}${item.alternatives ? `<p><b>替代解释：</b>${escape(Array.isArray(item.alternatives)?item.alternatives.map(label).join('；'):JSON.stringify(item.alternatives))}</p>` : ''}<p class="verify"><b>${item.verificationKey?'验证练习':'建议练习'}：</b>${escape(practice(item))}</p></article>`;
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title>
<style>:root{font-family:system-ui,-apple-system,"PingFang SC",sans-serif;color:#20332e;background:#f2f5f2;color-scheme:light}*{box-sizing:border-box}body{margin:0;padding:24px 16px}main{max-width:980px;margin:auto}h1{font-size:28px;letter-spacing:-.5px;margin:0 0 10px;overflow-wrap:anywhere}h2{font-size:19px;margin:0 0 14px}p{line-height:1.65;margin:9px 0;overflow-wrap:anywhere}.muted{color:#60706a}.card{background:white;border:1px solid #dfe7df;border-radius:16px;padding:20px;margin:16px 0}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.stat{background:#eaf1eb;padding:14px;border-radius:12px;overflow-wrap:anywhere}.stat b{font-size:21px;display:block;margin-top:5px}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}audio{width:100%;margin-top:12px}button{background:#215e48;color:white;border:0;border-radius:9px;min-height:38px;padding:8px 12px;cursor:pointer;font:inherit}button:focus-visible{outline:3px solid #d49642;outline-offset:3px}canvas{width:100%;height:260px;display:block}.segments{display:flex;gap:8px;flex-wrap:wrap}article{padding:16px 0;border-top:1px solid #e1e7e1}article:first-of-type{border-top:0}.verify{background:#f3f6ed;padding:12px;border-radius:8px}dl{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:5px 18px;font-size:13px}dt{color:#637168;overflow-wrap:anywhere}dd{margin:0;overflow-wrap:anywhere}.badge{background:#f7edd6;color:#715b2d;padding:5px 10px;border-radius:999px;font-size:13px}details summary{cursor:pointer;min-height:38px}.intro{max-width:750px}footer{font-size:13px;padding:10px 0 24px}a{color:#215e48}@media(max-width:600px){body{padding:16px 12px}.card{padding:16px}.stats{grid-template-columns:repeat(2,minmax(0,1fr))}h1{font-size:24px}canvas{height:220px}}</style>
<main><div class="row"><h1>${escape(title)}</h1><span class="badge">仅保存在本机</span></div>
<section class="card"><h2>先看数据质量</h2><p><b>${escape({ok:'可用于录音观察',limited:'有限，需要结合回听',insufficient:'证据不足'}[report.quality?.status] ?? report.quality?.status)}</b> · 录音 ${num(report.metadata?.durationSec)} 秒，可靠有声 ${num(report.quality?.effectiveVoicedSec)} 秒。</p><p class="muted">${escape((report.quality?.reasons??[]).map(label).join('；'))}</p><p class="intro">观察来自录音中的音高、响度、周期性和频谱。发声方式只能提出待验证的假设；麦克风、伴奏、元音、混响与分离残留都会影响结果。它不能直接确定声带闭合或诊断喉部状态。</p>${!comparison?'<p>没有独立参考，本报告不计算音准分。</p>':`<p>参考匹配：${escape({ready:'可用于配对音高比较',unscored:'未评分',rejected:'证据未通过'}[comparison.status]??comparison.status)}。${escape((comparison.reasons??[]).map(label).join('；'))}</p>`}${alignmentNote}</section>
<section class="card" id="priority"><h2>优先回听与练习 · 最多 3 项</h2><p class="muted">可测到的观察优先显示较长区间；先回听确认，再做对应短练习。主动颤音、滑音或弱收要结合音乐表达判断。</p>${priority.length?priority.map(row).join(''):'<p>当前阈值下没有突出观察。建议录制 3 秒舒适音高干声，确认音高和响度能否稳定；没有标记不等于发声已正确。</p>'}</section>
<section class="card"><h2>需要验证的声乐假设</h2><p class="muted">分离人声的假设最高为低可信度。以下证据和替代解释应结合回听，并用干声练习复核。</p>${hypotheses.length?hypotheses.map(row).join(''):'<p>证据不足，暂不推断气息、挤嗓或声带闭合。建议补录无伴奏的 3–5 秒舒适音高持续元音，以及一句自然音量的短乐句。</p>'}${report.summary?.hypothesisReasons?.length?`<p class="muted">未作更多推断的原因：${escape(report.summary.hypothesisReasons.map(label).join('；'))}</p>`:''}</section>
<section class="card"><h2>回听、曲线与乐句</h2><p class="muted">点击曲线跳到对应时间；片段按钮播放该区间。绿色为演唱；参考通过对齐时显示灰色虚线。空白区域表示没有可靠音高。MIDI 60 = C4，显示音高不等于音准。</p><audio id="audio" controls preload="metadata" src="${escape(audioUrl)}"></audio><canvas id="curve" aria-label="录音音高随时间变化曲线"></canvas><details><summary>乐句列表 · ${(report.segments??[]).length} 句</summary><div class="segments">${(report.segments??[]).map((s,i)=>`<button data-start="${s.start}" data-end="${s.end}">第 ${i+1} 句 · ${num(s.start)}–${num(s.end)} 秒</button>`).join('')||'<p>没有足够可靠的乐句。</p>'}</div></details>${referenceUrl?`<details><summary>回听独立参考</summary><audio controls preload="metadata" src="${escape(referenceUrl)}"></audio></details>`:''}</section>
<section class="card"><h2>完整统计与全部观察</h2><div class="stats"><div class="stat">常用音域 MIDI<b>${num(range?.lowMidi)}–${num(range?.highMidi)}</b></div><div class="stat">配对音准命中率<b>${Number.isFinite(comparison?.score)?num(comparison.score,0)+'%':'未评分'}</b></div><div class="stat">有效配对覆盖<b>${comparison?num(comparison.coverage*100)+'%':'—'}</b></div><div class="stat">可靠配对<b>${num(comparison?.matchedSec)} 秒</b></div></div>${comparison?`<p>固定偏移 ${num(comparison.offsetSec,3)} 秒，移调 ${num(comparison.transposeSemitones)} 半音。共同时间内可靠参考 ${num(comparison.eligibleReferenceSec)} 秒；参考检出覆盖 ${num(comparison.referenceCoverageRatio*100)}%；演唱检出 ${num(comparison.performanceDetectedSec)} 秒；未配对参考 ${num(comparison.unmatchedReferenceSec)} 秒。</p><p class="muted">命中率只统计配对成功的有声音高帧，阈值 ±${num(comparison.hitCents,0)} 音分，不能代表整首演唱完成度。${comparison.octaveDifferenceRatio>0.1?'存在整句近八度差，先核对主动换八度、移调或音高追踪。':''}</p>`:''}<details><summary>全部 ${issues.length} 项可测到的观察</summary>${issues.length?issues.map(row).join(''):'<p>没有达到观察阈值的区间。</p>'}</details><details><summary>分析参数与文件身份</summary><p>报告版本：${escape(report.schemaVersion??1)}；声源类型：${escape({vocal:'干声',separated:'已分离人声',mixed:'混音',unknown:'未知'}[report.metadata?.sourceKind]??report.metadata?.sourceKind)}；计算使用共享网页分析内核。</p>${metrics(report.parameters??{})}<dl><dt>回听文件</dt><dd>${escape(report.metadata?.audioIdentity?.name)}</dd><dt>SHA-256</dt><dd>${escape(report.metadata?.audioIdentity?.sha256)}</dd></dl><p><a href="analysis.json" download>下载本地分析 JSON</a></p></details></section>
<footer class="muted">本报告没有外部依赖，不会上传录音。若发声时有疼痛或持续不适，应停止相关练习并向合适的专业人员咨询。</footer></main>
<script id="data" type="application/json">${data}</script><script>
const report=JSON.parse(document.getElementById('data').textContent),audio=document.getElementById('audio'),canvas=document.getElementById('curve');let endAt=null;
document.querySelectorAll('[data-start]').forEach(button=>button.onclick=()=>{audio.currentTime=Number(button.dataset.start);endAt=Number(button.dataset.end);audio.play().catch(()=>{});});audio.addEventListener('timeupdate',()=>{if(endAt!==null&&audio.currentTime>=endAt){audio.pause();endAt=null;}draw();});audio.addEventListener('seeking',draw);
const frames=report.frames||[],duration=report.metadata.durationSec||frames.at(-1)?.t||1,comparison=report.comparison,reference=comparison?.alignmentTrusted?comparison.referenceFrames||[]:[];let low=48,high=84;for(const f of frames)if(Number.isFinite(f.midi)){low=Math.min(low,f.midi);high=Math.max(high,f.midi);}for(const f of reference)if(Number.isFinite(f.midi)){low=Math.min(low,f.midi+comparison.transposeSemitones);high=Math.max(high,f.midi+comparison.transposeSemitones);}low=Math.floor(low/12)*12;high=Math.ceil(high/12)*12;
function draw(){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const w=rect.width,h=rect.height,l=40,r=12,top=12,b=28,x=t=>l+t/duration*(w-l-r),y=m=>top+(high-m)/(high-low)*(h-top-b);c.font='12px system-ui';c.strokeStyle='#e1e8e1';c.fillStyle='#60706a';for(let m=low;m<=high;m+=12){c.beginPath();c.moveTo(l,y(m));c.lineTo(w-r,y(m));c.stroke();c.fillText(m,5,y(m)+4);}for(let i=0;i<=4;i++)c.fillText(Math.round(i*duration/4)+'s',x(i*duration/4)-8,h-5);c.save();c.beginPath();c.rect(l,top,w-l-r,h-top-b);c.clip();if(reference.length){c.strokeStyle='#a5aea5';c.setLineDash([4,3]);c.beginPath();let previous=null;for(const f of reference){const time=f.t-comparison.offsetSec;if(!Number.isFinite(f.midi)){previous=null;continue;}if(previous===null||time-previous>.12)c.moveTo(x(time),y(f.midi+comparison.transposeSemitones));else c.lineTo(x(time),y(f.midi+comparison.transposeSemitones));previous=time;}c.stroke();c.setLineDash([]);}c.strokeStyle='#267458';c.lineWidth=1.4;c.beginPath();let previous=null;for(const f of frames){if(!Number.isFinite(f.midi)){previous=null;continue;}if(previous===null||f.t-previous>.12)c.moveTo(x(f.t),y(f.midi));else c.lineTo(x(f.t),y(f.midi));previous=f.t;}c.stroke();c.strokeStyle='#d48c3c';c.beginPath();c.moveTo(x(audio.currentTime),top);c.lineTo(x(audio.currentTime),h-b);c.stroke();c.restore();}
canvas.onclick=e=>{const r=canvas.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(duration,(e.clientX-r.left-40)/(r.width-52)*duration));endAt=null;};new ResizeObserver(draw).observe(canvas);draw();
</script></html>`;
}
